// config.bin - 16:28:36 06/05/14, generated in 0.10 seconds
// Generated by unRap v1.06 by Kegetys
// Separate rootclasses: Disabled, Automatic comments: Enabled

#define TEast		0
#define TWest		1
#define TGuerrila		2
#define TCivilian		3
#define TSideUnknown		4
#define TEnemy		5
#define TFriendly		6
#define TLogic		7

#define private		0
#define protected		1
#define public		2

#define LockNo		0
#define LockCadet		1
#define LockYes		2

#define true	1
#define false	0

#define VSoft		0
#define VArmor		1
#define VAir		2

class CfgPatches {
	class pzn_PRACS_Heli_mini
	{
		units[] = {};
		weapons[] = {};
		requiredVersion = 1;
		requiredAddons[] = {"CAData", "CACharacters", "CACharacters2", "CAWeapons", "CAWeapons_E", "CAAir", "CAAir_e"};
		version = 1;
	};
};

class CfgVehicleClasses
{
	class AIRPRACS
	{
		side = 1;
		faction = "smd_racs_faction";
		displayName = "$STR_AIRPRACS";
	};
};

class CfgMagazines {
	class Default;	// External class reference
	class VehicleMagazine;	// External class reference
	class 6Rnd_TOW_HMMWV;	// External class reference
	
	class 4200Rnd_762x51_M240 : VehicleMagazine {
		scope = protected;
		ammo = "B_762x51_Ball";
		count = 4200;
		initSpeed = 805;
		tracersEvery = 1;
		maxLeadSpeed = 500;	// max estimated speed km/h
		nameSound = "cannon";
	};
};
class Mode_SemiAuto;	// External class reference
class Mode_Burst;	// External class reference
class Mode_FullAuto;	// External class reference

class cfgWeapons {
	class TOWLauncher;	// External class reference
	class M240_veh;	// External class reference
	class MGun;	// External class reference
	
	class PRACS_UH1N_M240 : M240_veh {
		bullet1[] = {"ca\sounds\weapons\shells\big_shell_metal_01", 0.0707946, 1, 15};
		bullet2[] = {"ca\sounds\weapons\shells\big_shell_metal_03", 0.0707946, 1, 15};
		bullet3[] = {"ca\sounds\weapons\shells\big_shell_metal_02", 0.0707946, 1, 15};
		bullet4[] = {"ca\sounds\weapons\shells\big_shell_metal_01", 0.0707946, 1, 15};
		bullet5[] = {"ca\sounds\weapons\shells\big_shell_dirt_01", 0.0707946, 1, 15};
		bullet6[] = {"ca\sounds\weapons\shells\big_shell_dirt_02", 0.0707946, 1, 15};
		bullet7[] = {"ca\sounds\weapons\shells\big_shell_dirt_03", 0.0707946, 1, 15};
		bullet8[] = {"ca\sounds\weapons\shells\big_shell_dirt_04", 0.0707946, 1, 15};
		bullet9[] = {"ca\sounds\weapons\shells\big_shell_soft_01", 0.0707946, 1, 15};
		bullet10[] = {"ca\sounds\weapons\shells\big_shell_soft_02", 0.0707946, 1, 15};
		bullet11[] = {"ca\sounds\weapons\shells\big_shell_soft_03", 0.0707946, 1, 15};
		bullet12[] = {"ca\sounds\weapons\shells\big_shell_soft_04", 0.0707946, 1, 15};
		soundBullet[] = {"bullet1", 0.083, "bullet2", 0.083, "bullet3", 0.083, "bullet4", 0.083, "bullet5", 0.083, "bullet6", 0.083, "bullet7", 0.083, "bullet8", 0.083, "bullet9", 0.083, "bullet10", 0.083, "bullet11", 0.083, "bullet12", 0.083};
		scope = protected;
		displayName = $STR_DN_M240;
		soundContinuous = 0;
		aiDispersionCoefY = 21;
		aiDispersionCoefX = 21;
		cursor = "Air_W_MG";
		cursorAim = "Air_Dot";
		cursorSize = 1;
		showAimCursorInternal = true;
		magazines[] = {"4200Rnd_762x51_M240"};
		magazineReloadTime = 5;
		canLock = LockYes;
		modes[] = {"manual", "close", "short", "medium", "far"};
		
		class manual : MGun {
			displayName = $STR_DN_M240;
			autoFire = true;
			begin1[] = {"x\acex_sm\addons\s_wep_mg\m240_fire1.wss", 1.77828, 1, 1700};
			begin2[] = {"x\acex_sm\addons\s_wep_mg\m240_fire2.wss", 1.77828, 1, 1700};
			begin3[] = {"x\acex_sm\addons\s_wep_mg\m240_fire3.wss", 1.77828, 1, 1700};
			soundbegin[] = {"begin1", 0.33, "begin2", 0.34, "begin3", 0.33};
			soundContinuous = 0;
			soundBurst = 1;
			reloadTime = 0.009;
			dispersion = 0.0012;
			showToPlayer = true;
			burst = 4;
			aiRateOfFire = 0.5;	// delay between shots at given distance
			aiRateOfFireDistance = 50;
			minRange = 1;
			minRangeProbab = 0.01;
			midRange = 2;
			midRangeProbab = 0.01;
			maxRange = 3;
			maxRangeProbab = 0.01;
		};
		
		class close : manual {
			showToPlayer = false;
			soundBurst = 0;
			burst = 10;
			aiRateOfFire = 0.5;	// delay between shots at given distance
			aiRateOfFireDistance = 50;
			minRange = 0;
			minRangeProbab = 0.05;
			midRange = 100;
			midRangeProbab = 0.58;
			maxRange = 200;
			maxRangeProbab = 0.04;
		};
		
		class short : close {
			burst = 8;
			aiRateOfFire = 2;	// delay between shots at given distance
			aiRateOfFireDistance = 300;
			minRange = 50;
			minRangeProbab = 0.05;
			midRange = 200;
			midRangeProbab = 0.58;
			maxRange = 400;
			maxRangeProbab = 0.04;
		};
		
		class medium : close {
			burst = 4;
			aiRateOfFire = 3;	// delay between shots at given distance
			aiRateOfFireDistance = 600;
			minRange = 300;
			minRangeProbab = 0.05;
			midRange = 400;
			midRangeProbab = 0.58;
			maxRange = 600;
			maxRangeProbab = 0.04;
		};
		
		class far : close {
			burst = 5;
			aiRateOfFire = 5;	// delay between shots at given distance
			aiRateOfFireDistance = 1000;
			minRange = 500;
			minRangeProbab = 0.05;
			midRange = 600;
			midRangeProbab = 0.4;
			maxRange = 800;
			maxRangeProbab = 0.01;
		};
	};
};

class TalkTopics;	// External class reference
class NewTurret;
class CfgVehicles {
	class All {};	
	class AllVehicles : All {};	
	class Air : AllVehicles {};	
	class Helicopter : Air {
		class NewTurret;	// External class reference
		class AnimationSources;	// External class reference
		class ViewPilot;	// External class reference
	};
	
	
	class UH1H_TK_EP1;
	class AH6X_EP1;
	class MH6J_EP1;
	class AH6J_EP1;
	class AH6J_EP1_SMD_MAGPI : AH6J_EP1 {
		scope = 1;
		side = 1;
		vehicleclass = "AIRPRACS";
		faction = "smd_racs_faction";
	};
	
	class AH6X_SMD_ATACS : AH6X_EP1 {
		scope = 1;
		side = 1;
		vehicleclass = "AIRPRACS";
		faction = "smd_racs_faction";
	};
	
	class AH6X_SMD_MAGPI : AH6X_EP1 {
		scope = 1;
		side = 1;
		vehicleclass = "AIRPRACS";
		faction = "smd_racs_faction";
	};	
	class AH6X_SMD_RACS : AH6X_EP1 {
		scope = 1;
		side = 1;
		vehicleclass = "AIRPRACS";
		faction = "smd_racs_faction";
	};
	
	class AH6X_SMD_RACS_DIGI : AH6X_EP1 {
		scope = 1;
		side = 1;
		vehicleclass = "AIRPRACS";
		faction = "smd_racs_faction";
	};
	class MH6J_SMD_MAGPI : MH6J_EP1 {
		scope = 1;
		side = 1;
		vehicleclass = "AIRPRACS";
		faction = "smd_racs_faction";
	};
	//addnew
	class ACE_AH6J_DAGR_FLIR;
	class TU_AH6J_AGM_FLIR: ACE_AH6J_DAGR_FLIR
	{
		class Turrets;
	};
	class TU_EH6E: TU_AH6J_AGM_FLIR
	{
		class Turrets : Turrets
		{
			class MainTurret;
		};
	};
	class ap_AH6X_SMD_ATACS : TU_EH6E {
		displayname = "AH6X (ATACS)";
		displaynameshort = "AH6X (ATACS)";
		side = 1;
		vehicleclass = "AIRPRACS";
		faction = "smd_racs_faction";
		hiddenselections[] = {"camo1"};
		hiddenselectionstextures[] = {"smd\smd_assets\vehicles\textures\smd_veh_ah6_atacs_co.paa"};
	};	
	class ap_AH6X_SMD_MAGPI : TU_EH6E {
		displayname = "AH6X (Mag P.I.)";
		displaynameshort = "AH6X (Mag P.I.)";
		side = 1;
		vehicleclass = "AIRPRACS";
		faction = "smd_racs_faction";
		hiddenselections[] = {"camo1"};
		hiddenselectionstextures[] = {"smd\smd_assets\vehicles\textures\smd_veh_ah6_magnumpi_co.paa"};
	};	
	class ap_AH6X_SMD_RACS : TU_EH6E {
		displayname = "AH6X (RACS)";
		displaynameshort = "AH6X (RACS)";
		side = 1;
		vehicleclass = "AIRPRACS";
		faction = "smd_racs_faction";
		hiddenselections[] = {"camo1"};
		hiddenselectionstextures[] = {"smd\smd_assets\vehicles\textures\smd_veh_ah6_racs_co.paa"};
	};	
	class ap_AH6X_SMD_RACS_DIGI : TU_EH6E {
		displayname = "AH6X (RACS) Digital";
		displaynameshort = "AH6X (RACS) Digital";
		side = 1;
		vehicleclass = "AIRPRACS";
		faction = "smd_racs_faction";
		hiddenselections[] = {"camo1"};
		hiddenselectionstextures[] = {"smd\smd_assets\vehicles\textures\smd_veh_ah6_racs_digi_co.paa"};
	};
	class ap_AH6X_SMD_PRESS : TU_EH6E {
		displayname = "AH6X PRESS";
		displaynameshort = "AH6X PRESS";
		side = 1;
		vehicleclass = "AIRPRACS";
		faction = "smd_racs_faction";
		hiddenselections[] = {"camo1"};
		hiddenselectionstextures[] = {"pracs_heli\tex\smd_veh_ah6_press_co.paa"};
		class Turrets : Turrets
		{
			class MainTurret: MainTurret
			{
				class OpticsIn
				{
					class camera
					{
						gunnerOpticsModel = "\ca\weapons\2Dscope_com1";
						initAngleX = 0;
						initAngleY = 0;
						initFov = "0.33333/1";
						maxAngleX = 30;
						maxAngleY = 100;
						maxFov = "0.33333/1";
						minAngleX = -30;
						minAngleY = -100;
						minFov = "0.33333/20";
						opticsDisplayName = "E";
						visionMode[] = {"Normal", "NVG"};
					};
				};
			};
		};
	};
	class AH6J_EP1_SMD_RACS_DIGI : AH6J_EP1 {
		displayname = "AH6J (RACS) Digital";
		displaynameshort = "AH6J (RACS) Digital";
		model = "\pracs_heli\ace_ah6_m134.p3d";
		side = 1;
		vehicleclass = "AIRPRACS";
		faction = "smd_racs_faction";
		hiddenselections[] = {"camo1", "camo2"};
		hiddenselectionstextures[] = {"pracs_heli\tex\smd_veh_ah6_racs_digi_co.paa", "ca\air_e\ah6j\data\default_co.paa"};
	};
	class ap_MH6J_SMD_RACS_DIGI : MH6J_EP1 {
		displayname = "MH6J (RACS) Digital";
		displaynameshort = "MH6J (RACS) Digital";
		model = "\pracs_heli\ace_mh6.p3d";
		side = 1;
		vehicleclass = "AIRPRACS";
		faction = "smd_racs_faction";
		hiddenSelections[] = {"camo1", "camo2"};
		hiddenselectionstextures[] = {"pracs_heli\tex\smd_veh_ah6_racs_digi_co.paa", "ca\air_e\ah6j\data\default_co.paa"};
	};
	
	class UH1H_SMD_ATACS : UH1H_TK_EP1 {
		side = 1;
		vehicleclass = "AIRPRACS";
		faction = "smd_racs_faction";
	};
	
	class UH1H_SMD_BLOPS : UH1H_TK_EP1 {
		side = 1;
		vehicleclass = "AIRPRACS";
		faction = "smd_racs_faction";
	};
	
	class UH1H_SMD_BLOPS_DIGI : UH1H_TK_EP1 {
		side = 1;
		vehicleclass = "AIRPRACS";
		faction = "smd_racs_faction";
	};
	
	class UH1H_SMD_RACS : UH1H_TK_EP1 {
		side = 1;
		vehicleclass = "AIRPRACS";
		faction = "smd_racs_faction";
	};
	
	class UH1H_SMD_RACS_DIGI : UH1H_TK_EP1 {
		side = 1;
		vehicleclass = "AIRPRACS";
		faction = "smd_racs_faction";
	};
	
	class UH1H_SMD_UN : UH1H_TK_EP1 {
		side = 1;
		vehicleclass = "Air";
		faction = "smd_racs_faction";
	};
	
	class pzn_uh1_h_cas;
	class uh1_h_SMD_cas: pzn_uh1_h_cas
	{
		side = 1;
		vehicleclass = "AIRPRACS";
		faction = "smd_racs_faction";
		hiddenSelectionsTextures[] =
			{
				"smd\smd_assets\vehicles\textures\smd_veh_uh1_racs_co.paa",
				"smd\smd_assets\vehicles\textures\smd_veh_uh1_racs_in_co.paa",
				"ca\air_E\UH1H\data\default_co.paa"
			};		
	};
	class AP_CH46;
	class PRACS_CH46 : AP_CH46
	{
		vehicleclass = "AIRPRACS";
		faction = "smd_racs_faction";
		hiddenSelectionsTextures[]=
		{
			"pracs_heli\tex\ch46_RACS_co.paa",
			"usarmy_heli\data\CH46\ch46_main_ti_ca.paa",
			"usarmy_heli\data\CH46\ch46_main_ti_ca.paa",
			"usarmy_heli\data\CH46\ch46_main_ti_ca.paa",
			"usarmy_heli\data\CH46\ch46_main_ti_ca.paa"
		};
	};
	class AP_CH53;
	class PRACS_CH53 : AP_CH53
	{
		vehicleclass = "AIRPRACS";
		faction = "smd_racs_faction";
		hiddenSelectionsTextures[]=
		{
			"pracs_heli\tex\ch53_RACS_co.paa",
			"usarmy_heli\data\CH53\ch53_ti_ca.paa",
			"usarmy_heli\data\CH53\ch53_ti_ca.paa",
			"usarmy_heli\data\CH53\ch53_ti_ca.paa",
			"usarmy_heli\data\CH53\ch53_ti_ca.paa"
		};
	};
	
	class PRACS_puma330 : Helicopter {
		scope = private;
		mapSize = 20;
		type = VAir;
		side = 1;
		faction = BIS_US;
		armor = 90;
		cost = 10000000;
		damageResistance = 0.00242;
		vehicleClass = "Air";
		irScanRangeMin = 500;
		crew = "USMC_Soldier_Pilot";
		driverInAction = "AH6_Pilot";
		driverAction = "AH6_Pilot";
		accuracy = 1000;	// accuracy needed to recognize type of this target
		camouflage = 60;	// how dificult to spot - bigger - better spotable
		fuelCapacity = 1000;
		initCargoAngleY = 10;
		minCargoAngleY = -60;
		maxCargoAngleY = 120;
		maxSpeed = 290;	// max speed on level road, km/h
		simulation = "helicopter";
		enableSweep = false;
		DriverCanSee = 1+2+8+32;
		supplyRadius = 2.5;
		memoryPointsGetInDriver = "pos_driver";
		memoryPointsGetInDriverDir = "pos_driver_dir";
		memoryPointsGetInCargo = "pos_cargo";
		memoryPointsGetInCargoDir = "pos_cargo_dir";
		castDriverShadow = true;
		castCargoShadow = true;
		audible = 50;	// audible - bigger - better heard
		insideSoundCoef = 0.4;
		gearRetracting = true;
		selectionHRotorStill = "velka vrtule staticka";
		selectionHRotorMove = "velka vrtule blur";
		selectionVRotorStill = "mala vrtule staticka";
		selectionVRotorMove = "mala vrtule blur";
		mainRotorSpeed = 1;
		backRotorSpeed = 1;
		minMainRotorDive = 9;
		maxMainRotorDive = -14;
		neutralMainRotorDive = 4;
		weapons[] = {"CMFlareLauncher"};
		magazines[] = {"120Rnd_CMFlare_Chaff_Magazine"};
		transportMaxMagazines = 150;
		transportMaxWeapons = 30;
		hiddenselections[] = {"num1", "num2"};
		extCameraPosition[] = {0, 1, -15};
		
		// threat (VSoft, VArmor, VAir), how threatening vehicle is to unit types
		threat[] = {1, 0.05, 0.05};

		soundGetIn[] = {"ca\sounds\Air\Mi17\ext\ext-Mi17-getin-01", db0, 1};
		soundGetOut[] = {"ca\sounds\Air\Mi17\ext\ext-Mi17-getout-01", db0, 1, 40};
		soundEnviron[] = {"", db-30, 1.0};
		soundDammage[] = {"ca\sounds\Air\Mi17\int\alarm_loop1", 0.000562341, 1};
		soundEngineOnInt[] = {"ca\sounds\Air\Mi17\int\int-Mi17-start-1a", 0.562341, 1.0};
		soundEngineOnExt[] = {"ca\sounds\Air\Mi17\ext\ext-Mi17-start-01a", 0.794328, 1.0, 700};
		soundEngineOffInt[] = {"ca\sounds\Air\Mi17\int\int-Mi17-stop-1a", 0.562341, 1.0};
		soundEngineOffExt[] = {"ca\sounds\Air\Mi17\ext\ext-Mi17-stop-01a", 0.794328, 1.0, 700};
		
		class Sounds {
			class Engine {
				sound[] = {"ca\sounds\air\Mi17\ext\ext-sovietheli-engine-6", 5.62341, 1.0, 900};
				frequency = "rotorSpeed";
				volume = "camPos*((rotorSpeed-0.72)*4)";
			};
			
			class RotorLowOut {
				sound[] = {"ca\sounds\air\Mi17\ext\ext-Mi17-rotor-low-2", db5, 1.0, 1400};
				frequency = "rotorSpeed";
				volume = "camPos*(0 max (rotorSpeed-0.1))";
				cone[] = {1.6, 3.14, 2.0, 0.95};
			};
			
			class RotorHighOut {
				sound[] = {"ca\sounds\air\Mi17\ext\ext-Mi17-rotor-high-2", db10, 1.0, 1650};
				frequency = "rotorSpeed";
				volume = "camPos*10*(0 max (rotorThrust-0.9))";
				cone[] = {1.6, 3.14, 2.0, 0.95};
			};
			
			class EngineIn {
				sound[] = {"ca\sounds\air\Mi17\int\int-sovietheli-engine-3", db0, 1.0};
				frequency = "rotorSpeed";
				volume = "(1-camPos)*((rotorSpeed-0.75)*4)";
			};
			
			class RotorLowIn {
				sound[] = {"ca\sounds\air\Mi17\int\int-Mi17-rotor-low-2", db5, 1.0};
				frequency = "rotorSpeed";
				volume = "(1-camPos)*(0 max (rotorSpeed-0.1))";
			};
			
			class RotorHighIn {
				sound[] = {"ca\sounds\air\Mi17\int\int-Mi17-rotor-high-2", db5, 1.0};
				frequency = "rotorSpeed";
				volume = "(1-camPos)*3*(rotorThrust-0.9)";
			};
		};
		
		class HitLGlass {
			armor = 0.7;
			material = 51;
			name = "sklo predni L";
			visual = "sklo predni L";
			passThrough = false;
		};
		
		class HitRGlass {
			armor = 0.7;
			material = 51;
			name = "sklo predni P";
			visual = "sklo predni P";
			passThrough = false;
		};
		
		class HitVRotor {
			armor = 0.3;
			material = 51;
			name = "mala vrtule";
			visual = "mala vrtule staticka";
			passThrough = false;
		};
		
		class HitHRotor {
			armor = 0.2;
			material = 51;
			name = "velka vrtule";
			visual = "velka vrtule staticka";
			passThrough = false;
		};
		dammageHalf[] = {"\PRACS_Heli\tex\puma\puma_glass_ca.paa", "\PRACS_Heli\tex\puma\puma_glassbr1_ca.paa"};
		dammageFull[] = {"\PRACS_Heli\tex\puma\puma_glass_ca.paa", "\PRACS_Heli\tex\puma\puma_glassbr2_ca.paa"};
		
		class Damage {
			tex[] = {};
			mat[] = {"PRACS_Heli\tex\puma\mat\puma1.rvmat", "PRACS_Heli\tex\puma\mat\puma1.rvmat", "PRACS_Heli\tex\puma\mat\puma1_destruct.rvmat", "PRACS_Heli\tex\puma\mat\puma2.rvmat", "PRACS_Heli\tex\puma\mat\puma2.rvmat", "PRACS_Heli\tex\puma\mat\puma2_destruct.rvmat", "PRACS_Heli\tex\puma\mat\puma_panel.rvmat", "PRACS_Heli\tex\puma\mat\puma_panel.rvmat", "PRACS_Heli\tex\puma\mat\puma_panel_destruct.rvmat", "PRACS_Heli\tex\puma\mat\puma_seat.rvmat", "PRACS_Heli\tex\puma\mat\puma_seat.rvmat", "PRACS_Heli\tex\puma\mat\puma_seat_destruct.rvmat"};
		};
	};
	class PlaneWreck;	// External class reference*/
	class PRACS_ch_46e_wreck : PlaneWreck {
		scope = protected;
		
		class Armory {
			disabled = 1;
		};
		model = "\PRACS_heli\PRACS_ch_46e_wreck.p3d";
		typicalCargo[] = {};
		irTarget = false;
		transportAmmo = 0;
		transportRepair = 0;
		transportFuel = 0;
		transportSoldier = 1;
		
		class Eventhandlers {};
	};
};